Repository chromaui/chromatic-cli, pull requests merged in 2019-10, with the labels that each got.

#12 Manually retry uploads, recreating streams each time
  bin/io/upload-to-s3.js
Labels: bug

#23 Add support for running in a github action
  bin/git/getCommitAndBranch.js
Labels: enhancement

#25 Fix/24 correct warn logging
  bin/tester/runtimes.js
Labels: bug

#28 Fix/paths
  .gitignore
  bin/lib/verify-option.js
  package.json
  stories/A.stories.js
  yarn.lock
Labels: bug

#33 ADD chroma bin
  package.json
Labels: bug

#37 FIX missing addons info in debug
  bin/__tests__/tester.test.js
  bin/tester/index.js
Labels: bug

#36 FIX 34 - respect the CHROMA_* env variables
  bin/constants.js
Labels: bug

#39 Add LICENSE file
  LICENSE
  bin/__tests__/tester.test.js
  bin/constants.js
  bin/tester/index.js
Labels: enhancement

#42 Tech/add test for GitHub action
  .github/workflows/chromatic.yml
Labels: enhancement

#43 Fix/GitHub actions
  .github/workflows/chromatic-action.yml
  .github/workflows/chromatic-manual.yml
  README.md
  bin/__tests__/tester.test.js
  bin/git/getCommitAndBranch.js
  bin/main.js
  bin/storybook/start-app.js
  bin/tester/index.js
  package.json
  scripts/publish.js
  yarn.lock
Labels: bug

#52 ADD svg polyfills
  bin/lib/jsdom-shims.js
Labels: customer reported, enhancement

#53 Allow use of Intl without new operator
  bin/lib/jsdom-shims.js
Labels: enhancement

#51 ADD unfetch as a fetch polyfill, as it's not in JSDom by default?
  bin/lib/jsdom-shims.js
Labels: customer reported, enhancement
