Repository chromaui/chromatic-cli, pull requests merged in 2019-11, with the labels that each got.

#54 v3.1.0
  bin/lib/jsdom-shims.js
Labels: enhancement

#56 ADD a workflow that runs on windows
  .github/workflows/chromatic-windows.yml
  .storybook/preview-head.html
  azure-pipelines.yml
  bin/__tests__/git.test.js
  bin/__tests__/serializers.test.js
  bin/git/git.js
  bin/io/upload-to-s3.js
  dist/storybook-addon.js
  dist/storybook-addon.js.map
  package.json
  static/css/global.css
  yarn.lock
Labels: bug

#55 IMPROVE logging when git fails
  bin/git/git.js
  bin/main.js
  bin/tester/index.js
Labels: bug, customer reported, enhancement

#60 Use prBranch when available
  bin/git/getCommitAndBranch.js
Labels: bug

#63 Add --exit-once-sent-to-chromatic flag
  README.md
  bin/__tests__/parseArgv.test.js
  bin/__tests__/tester.test.js
  bin/lib/verify-option.js
  bin/main.js
  bin/tester/index.js
  package.json
Labels: customer reported, enhancement
