Repository chromaui/chromatic-cli, pull requests merged in 2023-10, with the labels that each got.

#827 Fix dependency tracing for monorepos with no `package.json` at the repository root
  node-src/lib/findChangedDependencies.ts
Labels: patch

#833 Gracefully handle gpg signature info in `git log` output
  node-src/git/git.test.ts
  node-src/git/git.ts
Labels: patch

#826 Pass runtime metadata in `announceBuild`
  node-src/lib/getPackageManager.ts
  node-src/tasks/build.test.ts
  node-src/tasks/build.ts
  node-src/tasks/initialize.test.ts
  node-src/tasks/initialize.ts
  node-src/types.ts
  node-src/ui/messages/errors/buildFailed.stories.ts
  node-src/ui/messages/errors/buildFailed.ts
  node-src/ui/messages/errors/fatalError.stories.ts
  node-src/ui/messages/errors/fatalError.ts
  node-src/ui/tasks/build.stories.ts
  node-src/ui/tasks/build.ts
Labels: minor

#840 Fix reading `diagnostics` from undefined
  node-src/index.test.ts
  node-src/index.ts
  node-src/io/GraphQLClient.ts
  node-src/io/HTTPClient.ts
  node-src/io/getProxyAgent.ts
  node-src/lib/checkForUpdates.ts
  node-src/lib/checkPackageJson.ts
  node-src/lib/getConfiguration.ts
  node-src/lib/getOptions.ts
  node-src/lib/parseArgs.ts
  node-src/lib/writeChromaticDiagnostics.ts
  node-src/runBuild.ts
  node-src/tasks/report.ts
  node-src/types.ts
  node-src/ui/messages/errors/fatalError.ts
  node-src/ui/messages/warnings/outdatedPackage.ts
  package.json
  yarn.lock
Labels: patch

#841 Add workflow to require certain PR labels before merging
  .github/workflows/check-labels.yml
Labels: patch, skip-release

#845 Fix use of `LoggingRenderer` after bad merge
  node-src/index.ts
  node-src/runBuild.ts
Labels: release, patch

#843 Fix `ENOENT` when uploading stats file with `--upload-metadata`
  node-src/index.test.ts
  node-src/tasks/upload.ts
Labels: release, patch

#846 Fix config for Auto and add `next-release` tag to trigger a `next` release
   auto.config.ts
  .github/workflows/check-labels.yml
  package.json
Labels: patch, next-release

#847 Configure auto with `prerelease` setting and update readme
  README.md
  package.json
Labels: patch, next-release

#825 Merge Group (Queues) GitHub Action Event Support
  action-src/main.ts
Labels: github action, release, minor
