Repository chromaui/chromatic-cli, pull requests merged in 2023-12, with the labels that each got.

#865 Force `NODE_ENV=production` for Storybook builds through the CLI
  node-src/tasks/build.ts
Labels: release, major

#866 Increase number of commits checked for squash merge
  node-src/git/getParentCommits.test.ts
  node-src/git/getParentCommits.ts
  node-src/git/mocks/double-loop.ts
  node-src/git/mocks/mock-index.ts
Labels: release, minor

#870 Implement file hashing for to-be-uploaded files
  node-src/__mocks__/iframe.html
  node-src/__mocks__/index.html
  node-src/index.test.ts
  node-src/lib/getConfiguration.ts
  node-src/lib/getEnv.ts
  node-src/lib/getFileHashes.test.ts
  node-src/lib/getFileHashes.ts
  node-src/lib/getOptions.ts
  node-src/lib/parseArgs.ts
  node-src/tasks/upload.test.ts
  node-src/tasks/upload.ts
  node-src/types.ts
  node-src/ui/tasks/upload.stories.ts
  node-src/ui/tasks/upload.ts
  package.json
  yarn.lock
Labels: minor, skip-release

#873 Use code splitting in tsup CJS output
  tsup.config.ts
Labels: patch, skip-release

#876 Replace `getUploadUrls` with `uploadBuild` mutation
  node-src/index.test.ts
  node-src/index.ts
  node-src/lib/compress.ts
  node-src/lib/upload.ts
  node-src/lib/uploadFiles.ts
  node-src/lib/uploadMetadataFiles.ts
  node-src/lib/uploadZip.ts
  node-src/tasks/report.ts
  node-src/tasks/storybookInfo.test.ts
  node-src/tasks/upload.test.ts
  node-src/tasks/upload.ts
  node-src/tasks/verify.test.ts
  node-src/tasks/verify.ts
  node-src/types.ts
  node-src/ui/messages/errors/brokenStorybook.stories.ts
  node-src/ui/messages/errors/brokenStorybook.ts
  node-src/ui/messages/errors/fatalError.stories.ts
  node-src/ui/messages/errors/fatalError.ts
  node-src/ui/messages/errors/maxFileCountExceeded.stories.ts
  node-src/ui/messages/errors/maxFileCountExceeded.ts
  node-src/ui/messages/errors/maxFileSizeExceeded.stories.ts
  node-src/ui/messages/errors/maxFileSizeExceeded.ts
  node-src/ui/messages/info/storybookPublished.stories.ts
  node-src/ui/messages/info/storybookPublished.ts
  node-src/ui/tasks/upload.stories.ts
  node-src/ui/tasks/upload.ts
  package.json
  yarn.lock
Labels: minor, skip-release

#879 Allow overriding `NODE_ENV` with `STORYBOOK_NODE_ENV`
  node-src/lib/getEnv.ts
  node-src/tasks/build.test.ts
  node-src/tasks/build.ts
Labels: release, patch

#877 Run publish-action script as afterShipIt hook
  .github/workflows/release.yml
  package.json
  yarn.lock
Labels: patch, skip-release
