Repository chromaui/chromatic-cli, pull requests merged in 2024-11, with the labels that each got.

#1117 Ensure parent directory exists before writing log/diagnostics file
  node-src/index.test.ts
  node-src/lib/log.ts
  node-src/lib/writeChromaticDiagnostics.test.ts
  node-src/lib/writeChromaticDiagnostics.ts
Labels: release, patch

#1110 Account for `rsbuild` stats JSON output and multiple locations
  node-src/lib/getDependentStoryFiles.test.ts
  node-src/lib/getDependentStoryFiles.ts
  node-src/types.ts
Labels: release, patch

#1118 :sparkles: Add support for JSON5 as a configuration file.
  node-src/index.test.ts
  node-src/lib/getConfiguration.test.ts
  node-src/lib/getConfiguration.ts
  node-src/ui/messages/errors/unparseableConfigurationFile.stories.ts
  node-src/ui/messages/errors/unparseableConfigurationFile.ts
  package.json
  yarn.lock
Labels: release, minor

#1119 :book: Add new issue template that references Chromatic support.
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: patch, skip-release

#1112 Detect `context.projectMetadata.hasRouter` and send to the index
  node-src/git/git.test.ts
  node-src/git/git.ts
  node-src/index.test.ts
  node-src/lib/getHasRouter.test.ts
  node-src/lib/getHasRouter.ts
  node-src/tasks/gitInfo.test.ts
  node-src/tasks/gitInfo.ts
  node-src/tasks/initialize.ts
  node-src/tasks/storybookInfo.test.ts
  node-src/types.ts
Labels: enhancement, release, minor

#1121 Revert "Detect `context.projectMetadata.hasRouter` and send to the index"
  node-src/git/git.test.ts
  node-src/git/git.ts
  node-src/index.test.ts
  node-src/lib/getHasRouter.test.ts
  node-src/lib/getHasRouter.ts
  node-src/tasks/gitInfo.test.ts
  node-src/tasks/gitInfo.ts
  node-src/tasks/initialize.ts
  node-src/tasks/storybookInfo.test.ts
  node-src/types.ts
Labels: bug, release, patch

#1125 :sparkles: Add properties to XML reporting based on status.
  node-src/tasks/report.ts
  package.json
  yarn.lock
Labels: release, minor
