Repository chromaui/chromatic-cli, pull requests merged in 2024-07, with the labels that each got.

#1011 Add missing skipUpdateCheck option to config schema
  action-src/main.ts
  action.yml
  node-src/lib/getConfiguration.test.ts
  node-src/lib/getConfiguration.ts
Labels: release, patch

#1015 Support non-local ancestor builds with `uncommittedHash`
  node-src/git/findAncestorBuildWithCommit.test.ts
  node-src/git/findAncestorBuildWithCommit.ts
Labels: release, patch

#1016 Added logic to account for parentheses at the beginning
  node-src/tasks/upload.test.ts
  node-src/tasks/upload.ts
Labels: bug, release, minor

#1018 test setting outOfSync to false
  node-src/lib/findChangedDependencies.test.ts
  node-src/lib/getDependencies.ts
Labels: release, minor, prerelease
