Repository chromaui/chromatic-cli, pull requests merged in 2024-09, with the labels that each got.

#1028 Don't upload files from `.chromatic` directory
  node-src/tasks/upload.test.ts
  node-src/tasks/upload.ts
Labels: enhancement, release, minor

#1033 Fix initial TypeScript errors
  .codacy.yaml
  node-src/index.test.ts
  node-src/lib/checkForUpdates.ts
  node-src/tasks/initialize.test.ts
  package.json
  tsconfig.json
  vitest.config.ts
  vitest.no-threads.config.ts
  yarn.lock
Labels: minor, skip-release

#1034 Use the `--flag=value` format for Storybook build options
  node-src/tasks/build.test.ts
  node-src/tasks/build.ts
Labels: bug, release, patch

#1038 Remove Chromatic staging CI step
  .github/workflows/chromatic-staging.yml
Labels: patch, skip-release

#1039 Remove pre-commit hook
  .husky/pre-commit
  package.json
  yarn.lock
Labels: patch, skip-release

#1032 Support storybook-rsbuild
  node-src/lib/getDependentStoryFiles.test.ts
  node-src/lib/getDependentStoryFiles.ts
Labels: release, minor

#1042 Update actions/upload-artifact to v4
  .github/workflows/chromatic-main-and-prs.yml
  .github/workflows/chromatic-prod.yml
Labels: patch, skip-release

#1035 Use --stats-json flag for SB 8.0.0+
  node-src/tasks/build.test.ts
  node-src/tasks/build.ts
Labels: release, patch

#1043 Fix flaky missing dependency test
  node-src/lib/getStorybookInfo.test.ts
Labels: patch, skip-release

#1044 Fix flaky verify timeout test
  node-src/tasks/verify.test.ts
Labels: patch, skip-release

#1046 Revert "Use --stats-json flag for SB 8.0.0+"
  node-src/tasks/build.test.ts
  node-src/tasks/build.ts
Labels: release, patch

#1040 GitHub action to add package size comment to PR
  .github/workflows/package-size.yml
Labels: patch, skip-release

#1048 Enable`unicorn/no-array-for-each` ESLint rule
  eslint.config.mjs
  node-src/io/GraphQLClient.ts
  node-src/lib/compress.ts
  node-src/lib/findChangedDependencies.ts
  node-src/lib/getDependentStoryFiles.ts
  node-src/lib/getStorybookMetadata.ts
  node-src/lib/upload.ts
  node-src/lib/uploadFiles.ts
  node-src/lib/uploadZip.ts
  node-src/tasks/report.ts
Labels: patch, skip-release

#1047 Enable `unicorn/no-anonymous-default-export` ESLint rule
  eslint.config.mjs
  node-src/lib/getEnv.ts
  node-src/lib/spawn.ts
  node-src/tasks/index.ts
  tsconfig.eslint.json
Labels: patch, skip-release

#1050 Enable `unicorn/prefer-string-raw` ESLint rule
  eslint.config.mjs
  node-src/index.test.ts
  node-src/lib/getDependentStoryFiles.test.ts
  node-src/tasks/upload.test.ts
  node-src/tasks/upload.ts
Labels: patch, skip-release

#1051 Enable `unicorn/no-array-callback-reference` ESLint rule
  bin-src/trim-stats-file.ts
  eslint.config.mjs
  node-src/lib/e2e.ts
  node-src/lib/findChangedPackageFiles.ts
  node-src/lib/getDependentStoryFiles.ts
  node-src/lib/getStorybookMetadata.ts
  node-src/lib/promises.ts
  node-src/tasks/gitInfo.ts
  node-src/ui/messages/errors/uploadFailed.ts
  node-src/ui/messages/info/listingStories.ts
Labels: patch, skip-release

#1049 Use --stats-json flag for SB 8.0.0+
  node-src/tasks/build.test.ts
  node-src/tasks/build.ts
  node-src/types.ts
Labels: release, patch

#1055 Enable `unicorn/better-regex` ESLint rule
  eslint.config.mjs
  node-src/git/getParentCommits.test.ts
  node-src/git/git.ts
  node-src/lib/getDependencies.test.ts
  node-src/lib/getStorybookConfiguration.ts
  node-src/tasks/report.ts
  node-src/tasks/upload.ts
  node-src/ui/messages/warnings/deviatingOutputDir.ts
Labels: patch, skip-release

#1052 Enable `unicorn/prefer-spread` ESLint rule
  eslint.config.mjs
  node-src/git/getParentCommits.ts
  node-src/lib/getDependentStoryFiles.ts
  node-src/tasks/index.ts
  node-src/ui/messages/info/tracedAffectedFiles.ts
Labels: patch, skip-release

#1058 Revert "Use --stats-json flag for SB 8.0.0+"
  node-src/tasks/build.test.ts
  node-src/tasks/build.ts
  node-src/types.ts
Labels: release, patch

#1059 Track package size over time.
  .github/workflows/package-size-main.yml
  .github/workflows/package-size.yml
Labels: patch, skip-release

#1056 Enable `unicorn/no-array-reduce` ESLint rule
  eslint.config.mjs
  node-src/lib/compareBaseline.ts
  node-src/lib/getDependencies.ts
  node-src/lib/upload.ts
  node-src/tasks/initialize.ts
  node-src/ui/messages/info/tracedAffectedFiles.ts
Labels: patch, skip-release

#1057 Enable `unicorn/no-null` ESLint rule
  bin-src/init.ts
  bin-src/trim-stats-file.ts
  eslint.config.mjs
  node-src/git/findAncestorBuildWithCommit.test.ts
  node-src/git/findAncestorBuildWithCommit.ts
  node-src/git/getCommitAndBranch.test.ts
  node-src/git/git.test.ts
  node-src/git/git.ts
  node-src/index.test.ts
  node-src/lib/compress.ts
  node-src/lib/getDependentStoryFiles.test.ts
  node-src/lib/getDependentStoryFiles.ts
  node-src/lib/getFileHashes.ts
  node-src/lib/getPrebuiltStorybookMetadata.ts
  node-src/lib/getStorybookConfiguration.ts
  node-src/lib/getStorybookInfo.test.ts
  node-src/lib/getStorybookInfo.ts
  node-src/lib/getStorybookMetadata.ts
  node-src/lib/uploadMetadataFiles.ts
  node-src/tasks/build.ts
  node-src/tasks/gitInfo.test.ts
  node-src/tasks/gitInfo.ts
  node-src/tasks/initialize.ts
  node-src/ui/messages/errors/buildFailed.ts
  node-src/ui/messages/errors/fatalError.ts
  node-src/ui/messages/errors/uploadFailed.ts
  node-src/ui/messages/info/tracedAffectedFiles.ts
  node-src/ui/tasks/verify.stories.ts
  test-stories/Tests.stories.js
Labels: patch, skip-release

#1060 Include `storybookUrl` and `webUrl` on skipped rebuild
  node-src/tasks/gitInfo.test.ts
  node-src/tasks/gitInfo.ts
  node-src/types.ts
Labels: release, minor

#1061 Enable `unicorn/prefer-module` ESLint rule
  bin-src/register.js
  eslint.config.mjs
  isChromatic.js
  node-src/lib/checkStorybookBaseDirectory.test.ts
  node-src/lib/compareBaseline.test.ts
  node-src/lib/e2e.ts
  node-src/lib/getDependencies.test.ts
  node-src/lib/getStorybookMetadata.ts
  node-src/tasks/report.test.ts
  test-stories/timing.stories-disabled.js
Labels: patch, skip-release

#1066 Enable `eslint-plugin-jsdoc` ESLint rule
  bin-src/init.ts
  bin-src/main.ts
  bin-src/trace.ts
  bin-src/trim-stats-file.ts
  eslint.config.mjs
  node-src/git/findAncestorBuildWithCommit.ts
  node-src/git/generateGitRepository.ts
  node-src/git/getBaselineBuilds.ts
  node-src/git/getBranchFromMergeQueuePullRequestNumber.ts
  node-src/git/getChangedFilesWithReplacement.ts
  node-src/git/getCommitAndBranch.test.ts
  node-src/git/getCommitAndBranch.ts
  node-src/git/getParentCommits.ts
  node-src/git/git.ts
  node-src/git/mocks/mock-index.ts
  node-src/index.ts
  node-src/io/GraphQLClient.ts
  node-src/io/HTTPClient.ts
  node-src/io/getDNSResolveAgent.ts
  node-src/lib/FileReaderBlob.ts
  node-src/lib/LoggingRenderer.ts
  node-src/lib/NonTTYRenderer.ts
  node-src/lib/checkForUpdates.ts
  node-src/lib/checkPackageJson.ts
  node-src/lib/checkStorybookBaseDirectory.ts
  node-src/lib/compress.ts
  node-src/lib/e2e.ts
  node-src/lib/emailHash.ts
  node-src/lib/getConfiguration.ts
  node-src/lib/getDependentStoryFiles.ts
  node-src/lib/getEnvironment.ts
  node-src/lib/getOptions.test.ts
  node-src/lib/getOptions.ts
  node-src/lib/getStorybookConfiguration.test.ts
  node-src/lib/getStorybookConfiguration.ts
  node-src/lib/getStorybookInfo.ts
  node-src/lib/localBuildsSpecifier.ts
  node-src/lib/parseArguments.ts
  node-src/lib/spawn.ts
  node-src/lib/testLogger.ts
  node-src/lib/upload.ts
  node-src/lib/uploadFiles.ts
  node-src/lib/uploadMetadataFiles.ts
  node-src/lib/uploadZip.ts
  node-src/lib/waitForSentinel.ts
  node-src/lib/writeChromaticDiagnostics.ts
  node-src/tasks/index.ts
  node-src/ui/messages/errors/fatalError.ts
  node-src/ui/messages/errors/fetchError.ts
  node-src/ui/messages/errors/graphqlError.ts
  node-src/ui/messages/errors/runtimeError.ts
  node-src/ui/messages/errors/taskError.ts
  node-src/ui/messages/errors/uploadFailed.ts
  package.json
  test-stories/A.js
  test-stories/B.js
  test-stories/Star.js
  yarn.lock
Labels: patch, skip-release
