Repository chromaui/chromatic-cli, pull requests merged in 2024-10, with the labels that each got.

#1062 Enable `unicorn/filename-case` ESLint rule
  bin-src/register.js
  bin-src/trace.ts
  bin-src/trimStatsFile.test.ts
  bin-src/trimStatsFile.ts
  eslint.config.mjs
  node-src/__mocks__/dependencyChanges/berry-chalk-package.json
  node-src/__mocks__/dependencyChanges/berry-package.json
  node-src/git/getParentCommits.test.ts
  node-src/git/mocks/doubleLoop.ts
  node-src/git/mocks/longLine.ts
  node-src/git/mocks/longLoop.ts
  node-src/git/mocks/mockIndex.ts
  node-src/git/mocks/simpleLoop.ts
  node-src/git/mocks/threeParents.ts
  node-src/git/mocks/twoRoots.ts
  node-src/index.test.ts
  node-src/index.ts
  node-src/io/graphqlClient.ts
  node-src/io/httpClient.ts
  node-src/lib/fileReaderBlob.ts
  node-src/lib/loggingRenderer.ts
  node-src/lib/nonTTYRenderer.ts
  node-src/lib/uploadFiles.ts
  node-src/lib/uploadMetadataFiles.ts
  node-src/lib/uploadZip.ts
  node-src/tasks/readStatsFile.ts
  node-src/tasks/upload.test.ts
  node-src/tasks/upload.ts
  node-src/types.ts
  node-src/ui/messages/errors/graphqlError.stories.ts
  node-src/ui/messages/errors/graphqlError.ts
  subdir/package.json
  test-stories/a.js
  test-stories/aWrap.js
  test-stories/b.js
  test-stories/star.js
  test-stories/tests.stories.js
Labels: patch, skip-release

#1036 Add basic sentry integration to cli
  action-src/main.ts
  bin-src/main.ts
  node-src/errorMonitoring.ts
  node-src/index.ts
  node-src/lib/checkForUpdates.ts
  package.json
  yarn.lock
Labels: enhancement, minor, skip-release

#1067 Do not capture config/option exceptions
  node-src/index.ts
Labels: patch, skip-release

#1068 Filter ANSI escape codes for Sentry
  node-src/errorMonitoring.test.ts
  node-src/errorMonitoring.ts
  package.json
  tsup.config.ts
  yarn.lock
Labels: patch, skip-release

#1069 Annotate Sentry events
  node-src/errorMonitoring.ts
  node-src/tasks/initialize.test.ts
  node-src/tasks/initialize.ts
  node-src/tasks/storybookInfo.ts
Labels: patch, skip-release

#1071 Add `Empathy` and `CLI` labels to issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: patch, skip-release

#1072 Fix remaining TypeScript errors and unable `strict: true`
  action-src/main.ts
  bin-src/init.ts
  bin-src/trimStatsFile.ts
  node-src/errorMonitoring.test.ts
  node-src/errorMonitoring.ts
  node-src/git/findAncestorBuildWithCommit.ts
  node-src/git/getChangedFilesWithReplacement.ts
  node-src/git/getCommitAndBranch.test.ts
  node-src/git/getParentCommits.ts
  node-src/git/git.ts
  node-src/git/mocks/longLine.ts
  node-src/index.ts
  node-src/io/getProxyAgent.ts
  node-src/io/graphqlClient.ts
  node-src/lib/checkStorybookBaseDirectory.ts
  node-src/lib/compress.ts
  node-src/lib/findChangedDependencies.ts
  node-src/lib/findChangedPackageFiles.ts
  node-src/lib/getDependentStoryFiles.ts
  node-src/lib/getFileHashes.ts
  node-src/lib/getOptions.ts
  node-src/lib/getPackageManager.ts
  node-src/lib/getPrebuiltStorybookMetadata.ts
  node-src/lib/getStorybookMetadata.ts
  node-src/lib/localBuildsSpecifier.ts
  node-src/lib/tasks.ts
  node-src/lib/uploadMetadataFiles.ts
  node-src/lib/utils.ts
  node-src/tasks/build.ts
  node-src/tasks/initialize.ts
  node-src/tasks/report.ts
  node-src/tasks/snapshot.ts
  node-src/tasks/upload.ts
  node-src/types.ts
  tsconfig.json
Labels: patch, skip-release

#1073 Ignore duplication in test files and ignore all __mocks__
  .codacy.yaml
Labels: patch, skip-release

#1077 Upgrade `subdir` deps
  subdir/.storybook/main.js
  subdir/package.json
  subdir/yarn.lock
Labels: patch, skip-release

#1078 Add TypeScript checking to CI pipeline
  .circleci/config.yml
Labels: patch, skip-release

#1081 Show steps for initializing a new Git repo
  node-src/ui/messages/errors/gitNotInitialized.stories.ts
  node-src/ui/messages/errors/gitNotInitialized.ts
Labels: release, minor

#1082 Do not run Sentry in dev
  node-src/errorMonitoring.ts
Labels: patch, skip-release

#1083 Account for `--exit-zero-on-changes=true`
  node-src/tasks/snapshot.test.ts
  node-src/tasks/snapshot.ts
Labels: patch, skip-release

#1084 Add Sentry Releases
  .github/workflows/package-size-main.yml
  .github/workflows/package-size.yml
  .github/workflows/release.yml
  node-src/errorMonitoring.ts
  package.json
  scripts/versionAndBuild.mjs
  scripts/versionAndBuildForRelease.mjs
  tsup.config.ts
  vitest.config.ts
  yarn.lock
Labels: release, patch

#1085 Migrate linting and tests to GitHub Actions
  .circleci/config.yml
  .github/workflows/lint-and-test.yml
  node-src/git/getCommitAndBranch.test.ts
Labels: patch, skip-release

#1088 Move deployment to single script
  package.json
  scripts/publishAction.mjs
  scripts/release.mjs
  yarn.lock
Labels: release, patch

#1089 Manually update `package.json` and `CHANGELOG.md`
  CHANGELOG.md
  package.json
Labels: release, patch

#1090 Manually update `package.json` and `CHANGELOG.md` v2
  CHANGELOG.md
  package.json
Labels: release, patch

#1091 Manually update `package.json` and `CHANGELOG.md` v3
  CHANGELOG.md
  package.json
Labels: release, patch

#1092 Manually update `package.json` and `CHANGELOG.md` v4
  CHANGELOG.md
  package.json
Labels: release, patch

#1093 Fix GITHUB_REF check on release
  scripts/release.mjs
Labels: patch, skip-release

#1095 Add nicer formatting to TS bail reasons.
  .github/workflows/smoke-test-node-api.yml
  node-src/types.ts
  node-src/ui/messages/info/tracedAffectedFiles.stories.ts
  node-src/ui/messages/info/tracedAffectedFiles.ts
Labels: release, patch

#1098 Add new check to test the CLI action in merge queue
  .github/workflows/lint-and-test.yml
  .github/workflows/smoke-test-action-next.yml
  package.json
  scripts/releaseNext.mjs
Labels: minor, skip-release

#1100 Rename new action job name for merge queue UI
  .github/workflows/lint-and-test.yml
  .github/workflows/smoke-test-action-next.yml
Labels: patch, skip-release

#1102 Setup workflow for PR checks
  .github/workflows/chromatic-prod.yml
  .github/workflows/lint-and-test.yml
  .github/workflows/package-size.yml
  .github/workflows/pull-request-workflow.yml
  .github/workflows/smoke-test-action-next.yml
  .github/workflows/smoke-test-action.yml
  .github/workflows/smoke-test-node-api.yml
  .github/workflows/smoke-test-node18.yml
  .github/workflows/smoke-test-node20.yml
  .github/workflows/smoke-test-npx.yml
  .github/workflows/smoke-test-windows.yml
  .github/workflows/smoke-test-yarn-berry.yml
  .github/workflows/smoke-test-yarn-canary.yml
  .github/workflows/smoke-test-yarn-classic.yml
  .github/workflows/smoke-test-yarn.yml
  node-src/git/getCommitAndBranch.test.ts
Labels: patch, skip-release

#1101 Better handling of undefined values in branches
  node-src/tasks/gitInfo.test.ts
  node-src/tasks/gitInfo.ts
  node-src/ui/messages/warnings/undefinedBranchOwner.stories.ts
  node-src/ui/messages/warnings/undefinedBranchOwner.ts
  package.json
  yarn.lock
Labels: patch, skip-release

#1105 Only run `package-size` on pull request
  .github/workflows/pull-request-workflow.yml
Labels: patch, skip-release

#1106 Switch to read-package-up from read-pkg-up
  bin-src/init.test.ts
  bin-src/init.ts
  node-src/index.ts
  package.json
  yarn.lock
Labels: patch, skip-release

#1107 Add support for `logLevel` and `logPrefix` options, use local timestamp as default prefix
  action-src/main.ts
  action.yml
  node-src/index.ts
  node-src/lib/log.test.ts
  node-src/lib/log.ts
  node-src/lib/parseArguments.ts
  node-src/types.ts
Labels: release, minor

#1109 Add support for `--build-command` for arbitrary build commands
  action-src/main.ts
  action.yml
  node-src/lib/getConfiguration.ts
  node-src/lib/getOptions.ts
  node-src/lib/parseArguments.ts
  node-src/tasks/build.test.ts
  node-src/tasks/build.ts
  node-src/tasks/upload.ts
  node-src/types.ts
  node-src/ui/messages/errors/buildFailed.stories.ts
  node-src/ui/messages/errors/buildFailed.ts
  vitest.config.ts
Labels: release, minor

#1108 Handle ENOENT for bun as well as Node
  node-src/lib/getConfiguration.ts
Labels: release, patch

#1113 Add steps for how to run builds against local CLI
  README.md
  docs/DEVELOPMENT.md
  scripts/release.mjs
Labels: patch, skip-release
