Repository chromaui/chromatic-cli, pull requests merged in 2024-05, with the labels that each got.

#974 Properly check `storybookBaseDir` against repository root rather than CWD
  node-src/lib/checkStorybookBaseDir.test.ts
  node-src/lib/checkStorybookBaseDir.ts
Labels: release, patch

#976 Use current working directory as default value for `storybookBaseDir`
  node-src/lib/checkStorybookBaseDir.test.ts
  node-src/lib/checkStorybookBaseDir.ts
Labels: release, patch

#986 Fix type declaration for `isChromatic` import
  package.json
Labels: bug, release, patch

#982 Fix dependency tracing when running from a subdirectory
  node-src/git/git.test.ts
  node-src/git/git.ts
  node-src/lib/findChangedDependencies.test.ts
  node-src/lib/findChangedDependencies.ts
Labels: release, patch

#985 Use double quotes around command arguments
  node-src/git/git.test.ts
  node-src/git/git.ts
Labels: release, patch

#979 Remove console log
  node-src/lib/e2e.ts
Labels: patch, skip-release

#990 Setup Slack plugin for auto to notify on new CLI releases
  .circleci/config.yml
  package.json
  yarn.lock
Labels: patch, skip-release

#991 Pass `CI=1` environment variable to Storybook build command to disable prompts
  node-src/tasks/build.test.ts
  node-src/tasks/build.ts
Labels: release, patch

#992 Pass `SLACK_WEBHOOK_URL` to release script
  .github/workflows/release.yml
Labels: release, patch

#989 Upgrade Storybook to 8.1
  .circleci/config.yml
  .github/workflows/chromatic-main-and-prs.yml
  .github/workflows/chromatic-prod.yml
  .github/workflows/chromatic-staging.yml
  .github/workflows/release.yml
  .github/workflows/smoke-test-action.yml
  .github/workflows/smoke-test-node-api.yml
  .github/workflows/smoke-test-node18.yml
  .github/workflows/smoke-test-node20.yml
  .github/workflows/smoke-test-npx.yml
  .github/workflows/smoke-test-windows.yml
  .github/workflows/smoke-test-yarn-berry.yml
  .github/workflows/smoke-test-yarn-canary.yml
  .github/workflows/smoke-test-yarn-classic.yml
  .github/workflows/smoke-test-yarn.yml
  .gitignore
  .storybook/main.js
  .storybook/main.ts
  .storybook/preview.js
  .storybook/preview.tsx
  .yarnrc.yml
  bin-src/__mocks__/normalProjectJson/project.json
  bin-src/__mocks__/previewStatsJson/preview-stats.trimmed.json
  bin-src/__mocks__/unsupportedAddons/project.json
  bin-src/trace.test.ts
  bin-src/trim-stats-file.test.ts
  node-src/__mocks__/dependencyChanges/berry-chalk-package.json
  node-src/__mocks__/dependencyChanges/berry-chalk-yarn.lock
  node-src/__mocks__/dependencyChanges/berry-package.json
  node-src/__mocks__/dependencyChanges/berry-yarn.lock
  node-src/__mocks__/dependencyChanges/plain-yarn.lock
  node-src/__mocks__/dependencyChanges/react-async-10-yarn.lock
  node-src/__mocks__/dependencyChanges/react-async-9-yarn.lock
  node-src/index.test.ts
  node-src/lib/builders.ts
  node-src/lib/getDependencies.test.ts
  node-src/lib/getPrebuiltStorybookMetadata.ts
  node-src/lib/getStorybookInfo.test.ts
  node-src/lib/supportedAddons.ts
  node-src/lib/viewLayers.ts
  node-src/tasks/build.test.ts
  node-src/tasks/initialize.test.ts
  package.json
  scripts/rename.js
  yarn.lock
Labels: release, minor
