Repository chromaui/chromatic-cli, pull requests merged in 2024-12, with the labels that each got.

#1122 Send project metadata to the index
  bin-src/trace.ts
  node-src/git/execGit.test.ts
  node-src/git/execGit.ts
  node-src/git/getParentCommits.ts
  node-src/git/git.test.ts
  node-src/git/git.ts
  node-src/index.test.ts
  node-src/lib/findChangedPackageFiles.test.ts
  node-src/lib/findChangedPackageFiles.ts
  node-src/lib/getDependentStoryFiles.test.ts
  node-src/lib/getDependentStoryFiles.ts
  node-src/lib/getHasRouter.test.ts
  node-src/lib/getHasRouter.ts
  node-src/lib/getStorybookBaseDirectory.test.ts
  node-src/lib/getStorybookBaseDirectory.ts
  node-src/lib/posix.ts
  node-src/tasks/gitInfo.test.ts
  node-src/tasks/gitInfo.ts
  node-src/tasks/initialize.test.ts
  node-src/tasks/initialize.ts
  node-src/tasks/storybookInfo.test.ts
  node-src/tasks/storybookInfo.ts
  node-src/types.ts
Labels: enhancement, release, minor

#1129 Only publish `latest` action on push to main
  scripts/release.mjs
Labels: release, patch

#1130 Account for configs when checking `exitOnceUploaded` in action
  action-src/main.ts
Labels: release, patch

#1131 Errors in project metadata gathering causing build failures
  node-src/git/git.test.ts
  node-src/git/git.ts
  node-src/tasks/gitInfo.ts
Labels: release, patch

#1132 Upload coverage reports to codecov
  .github/workflows/lint-and-test.yml
  .github/workflows/pull-request-workflow.yml
Labels: minor, skip-release, internal
