Repository chromaui/chromatic-cli, pull requests merged in 2024-01, with the labels that each got.

#883 Revert "Replace `getUploadUrls` with `uploadBuild` mutation"
  node-src/index.test.ts
  node-src/index.ts
  node-src/lib/compress.ts
  node-src/lib/upload.ts
  node-src/lib/uploadFiles.ts
  node-src/lib/uploadMetadataFiles.ts
  node-src/lib/uploadZip.ts
  node-src/tasks/report.ts
  node-src/tasks/storybookInfo.test.ts
  node-src/tasks/upload.test.ts
  node-src/tasks/upload.ts
  node-src/tasks/verify.test.ts
  node-src/tasks/verify.ts
  node-src/types.ts
  node-src/ui/messages/errors/brokenStorybook.stories.ts
  node-src/ui/messages/errors/brokenStorybook.ts
  node-src/ui/messages/errors/fatalError.stories.ts
  node-src/ui/messages/errors/fatalError.ts
  node-src/ui/messages/errors/maxFileCountExceeded.stories.ts
  node-src/ui/messages/errors/maxFileCountExceeded.ts
  node-src/ui/messages/errors/maxFileSizeExceeded.stories.ts
  node-src/ui/messages/errors/maxFileSizeExceeded.ts
  node-src/ui/messages/info/storybookPublished.stories.ts
  node-src/ui/messages/info/storybookPublished.ts
  node-src/ui/tasks/upload.stories.ts
  node-src/ui/tasks/upload.ts
  package.json
  yarn.lock
Labels: release, patch

#878 Retrieve `sentinelUrls` from `uploadBuild` and wait for all of them before finishing upload task
  node-src/index.test.ts
  node-src/lib/FileReaderBlob.ts
  node-src/lib/upload.ts
  node-src/lib/uploadFiles.ts
  node-src/lib/uploadZip.ts
  node-src/lib/utils.ts
  node-src/lib/waitForSentinel.ts
  node-src/tasks/upload.test.ts
  node-src/tasks/upload.ts
  node-src/types.ts
  node-src/ui/messages/info/storybookPublished.stories.ts
  node-src/ui/tasks/upload.stories.ts
  node-src/ui/tasks/upload.ts
  package.json
  yarn.lock
Labels: patch, skip-release

#875 Deduplicate files to be uploaded using file hashing
  node-src/lib/upload.ts
  node-src/tasks/upload.test.ts
Labels: minor, skip-release

#884 Detect merge queue branch and retrieve real branch name from pull request
  node-src/git/getBranchFromMergeQueuePullRequestNumber.ts
  node-src/git/getCommitAndBranch.test.ts
  node-src/git/getCommitAndBranch.ts
  node-src/git/git.test.ts
  node-src/git/git.ts
  node-src/index.test.ts
Labels: minor, skip-release

#892 Fix potential zip upload error when deduping files on a very large Storybook
  node-src/lib/upload.ts
  node-src/lib/waitForSentinel.ts
  node-src/tasks/upload.test.ts
  node-src/tasks/upload.ts
Labels: bug, release, patch

#880 Add new Init command for Project Setup
  .gitignore
  bin-src/init.test.ts
  bin-src/init.ts
  bin-src/register.js
  node-src/lib/checkPackageJson.ts
  package.json
  yarn.lock
Labels: release, minor

#882 Add `--playwright` & `--cypress` flags
  action-src/main.ts
  action.yml
  node-src/index.test.ts
  node-src/index.ts
  node-src/lib/getConfiguration.ts
  node-src/lib/getE2eBinPath.ts
  node-src/lib/getOptions.ts
  node-src/lib/setExitCode.ts
  node-src/tasks/build.ts
  node-src/types.ts
  node-src/ui/messages/errors/missingDependency.stories.ts
  node-src/ui/messages/errors/missingDependency.ts
  package.json
Labels: release, minor

#901 Don't skip uploading of empty files, it works now
  node-src/lib/upload.ts
  node-src/tasks/upload.test.ts
  node-src/ui/messages/warnings/skippingEmptyFiles.stories.ts
  node-src/ui/messages/warnings/skippingEmptyFiles.ts
Labels: patch, skip-release

#894 Improve logging around upload errors
  node-src/io/HTTPClient.ts
  node-src/lib/log.ts
  node-src/lib/upload.ts
  node-src/lib/uploadFiles.ts
  node-src/lib/waitForSentinel.ts
  node-src/ui/messages/errors/uploadFailed.stories.ts
  node-src/ui/messages/errors/uploadFailed.ts
Labels: patch, skip-release

#900 Add "package.json" to exports map
  package.json
Labels: bug, release, patch

#902 Remove latest from the chromatic package in Init script
  bin-src/init.test.ts
  bin-src/init.ts
Labels: release, patch

#899 CLI should throw error when using TurboSnap but missing a stats file.
  node-src/tasks/upload.ts
  node-src/ui/messages/errors/missingStatsFile.stories.ts
  node-src/ui/messages/errors/missingStatsFile.ts
Labels: release, minor

#906 Remove after-release script
  package.json
Labels: release, patch
