Repository chromaui/chromatic-cli, pull requests merged in 2024-03, with the labels that each got.

#929 Allow commit hash to not be known when finding merge queue PR number
  node-src/git/getCommitAndBranch.ts
  node-src/git/git.test.ts
  node-src/git/git.ts
Labels: release, patch

#938 Allow commit hash to not be known when finding merge queue PR number [with github secrets]
  node-src/git/getCommitAndBranch.ts
  node-src/git/git.test.ts
  node-src/git/git.ts
Labels: release, patch

#937 Fix support for boolean value to `junitReport` option
  node-src/tasks/report.test.ts
  node-src/tasks/report.ts
Labels: release, patch

#932 Display full error message when storybookBaseDir is invalid
  node-src/lib/checkStorybookBaseDir.ts
  node-src/tasks/upload.test.ts
Labels: release, patch

#941 Do not prompt to install chromatic script during E2E builds
  node-src/index.test.ts
  node-src/index.ts
  node-src/lib/e2e.ts
  node-src/lib/getOptions.ts
  node-src/tasks/build.ts
Labels: release, patch

#942 escape special characters in onlyStoryFiles filenames
  node-src/tasks/upload.test.ts
  node-src/tasks/upload.ts
Labels: release, patch

#940 Expose E2E build errors
  node-src/lib/setExitCode.ts
  node-src/tasks/build.test.ts
  node-src/tasks/build.ts
  node-src/ui/messages/errors/e2eBuildFailed.stories.ts
  node-src/ui/messages/errors/e2eBuildFailed.ts
Labels: release, patch

#931 Prevent non-string or null message in timestamp logging from causing exit code 254 during build.
  node-src/lib/log.ts
Labels: release, patch

#943 Fix e2e peer dep versions
  package.json
Labels: release, patch

#948 Tell SB8 users to pass `--stats-json` rather than `--webpack-stats-json`
  node-src/tasks/upload.ts
  node-src/ui/messages/errors/missingStatsFile.stories.ts
  node-src/ui/messages/errors/missingStatsFile.ts
Labels: patch, skip-release

#946 Restrict permissions in GitHub Action workflows
  .github/workflows/check-labels.yml
  .github/workflows/chromatic-main-and-prs.yml
  .github/workflows/chromatic-prod.yml
  .github/workflows/chromatic-staging.yml
  .github/workflows/release.yml
  .github/workflows/smoke-test-action.yml
  .github/workflows/smoke-test-node-api.yml
  .github/workflows/smoke-test-node18.yml
  .github/workflows/smoke-test-node20.yml
  .github/workflows/smoke-test-npx.yml
  .github/workflows/smoke-test-windows.yml
  .github/workflows/smoke-test-yarn-berry.yml
  .github/workflows/smoke-test-yarn-canary.yml
  .github/workflows/smoke-test-yarn-classic.yml
  .github/workflows/smoke-test-yarn.yml
Labels: patch, skip-release

#947 Fixes for various issues reported by Codacy
  SUPPORT.md
  node-src/tasks/build.ts
  node-src/tasks/upload.ts
Labels: patch, skip-release

#928 Add `skipUpdateCheck` option
  node-src/lib/checkForUpdates.ts
  node-src/lib/getOptions.ts
  node-src/lib/parseArgs.ts
  node-src/types.ts
Labels: release, minor

#956 Fix GitHub Action release script using data from Auto shipIt hook rather than from Git
  node-src/types.ts
  node-src/ui/messages/errors/fatalError.ts
  package.json
  scripts/publish-action.mjs
Labels: patch, skip-release

#951 Properly handle GitHub Action inputs that can have multiple values
  action-src/main.ts
Labels: release, patch

#934 Allow passing both `buildScriptName` and `storybookBuildDir`
  node-src/lib/getOptions.test.ts
  node-src/lib/getOptions.ts
Labels: release, minor

#959 [trigger] Feature/allow build dir and build script name
  node-src/lib/getOptions.test.ts
  node-src/lib/getOptions.ts
Labels: release, minor

#960 Trim `v` prefix from shipIt's version to avoid double prefixing tags
  scripts/publish-action.mjs
Labels: patch, skip-release

#961 Throw user-friendly error when config file fails to parse as JSON
  node-src/lib/getConfiguration.test.ts
  node-src/lib/getConfiguration.ts
Labels: release, minor

#962 Suppress issues caused by missing Git remote
  node-src/git/git.ts
  node-src/tasks/gitInfo.ts
Labels: patch, skip-release
