Repository chromaui/chromatic-cli, pull requests merged in 2024-02, with the labels that each got.

#909 Rename E2E peer dependencies
  action.yml
  bin-src/init.test.ts
  bin-src/init.ts
  node-src/lib/getE2eBinPath.ts
  node-src/ui/messages/errors/missingDependency.stories.ts
  package.json
Labels: release, minor

#910 Add Fallback getGitInfo if we cannot find the origin URL
  node-src/index.test.ts
  node-src/index.ts
Labels: release, patch

#907 Add timestamps to debug and file logging
  node-src/lib/log.ts
Labels: minor, skip-release

#897 Support `env`, `sessionId` and `log` options via Node API
  node-src/index.ts
  node-src/types.ts
Labels: minor, skip-release

#913 Expose `repositoryRootDir`, `configFile` and fix `diagnosticsFile`
  node-src/index.ts
  node-src/lib/getConfiguration.test.ts
  node-src/lib/getConfiguration.ts
Labels: release, minor

#917 Directly execute build-archive-storybook if we can't resolve it
  action-src/main.ts
  node-src/index.test.ts
  node-src/lib/getE2eBinPath.ts
  node-src/lib/getE2eBuildCommand.ts
  node-src/lib/getOptions.ts
  node-src/tasks/build.ts
  node-src/types.ts
  node-src/ui/messages/errors/missingDependency.stories.ts
  node-src/ui/messages/errors/missingDependency.ts
Labels: release, patch

#919 clean up debug log as it's too much noise
  node-src/lib/getDependentStoryFiles.ts
Labels: release, patch

#916 Allow `traceChanged` in Chromatic config spec
  node-src/lib/getConfiguration.test.ts
  node-src/lib/getConfiguration.ts
Labels: release, patch

#920 Fix Storybook published messaging
  .github/workflows/chromatic-prod.yml
  node-src/tasks/verify.ts
  node-src/ui/messages/info/storybookPublished.stories.ts
  node-src/ui/messages/info/storybookPublished.ts
Labels: release, patch

#922 Avoid build verify timeout when waiting for upgrade builds
  node-src/index.ts
  node-src/lib/getEnv.ts
  node-src/lib/setExitCode.ts
  node-src/lib/waitForSentinel.ts
  node-src/tasks/verify.test.ts
  node-src/tasks/verify.ts
  node-src/ui/tasks/verify.stories.ts
  node-src/ui/tasks/verify.ts
  scripts/run-via-node.mjs
Labels: release, patch

#921 Add new invalid sb base dir error message and validator function
  node-src/__mocks__/storybookBaseDir/subdir/test.js
  node-src/__mocks__/storybookBaseDir/subdir/test.jsx
  node-src/__mocks__/storybookBaseDir/subdir/test.tsx
  node-src/__mocks__/storybookBaseDir/test.ts
  node-src/index.test.ts
  node-src/lib/checkStorybookBaseDir.test.ts
  node-src/lib/checkStorybookBaseDir.ts
  node-src/tasks/upload.test.ts
  node-src/tasks/upload.ts
  node-src/ui/messages/errors/invalidStorybookBaseDir.stories.ts
  node-src/ui/messages/errors/invalidStorybookBaseDir.ts
  package.json
  yarn.lock
Labels: release, major
