Repository chromaui/chromatic-cli, pull requests merged in 2025-01, with the labels that each got.

#1134 Set `storybookUrl` action output on rebuild early exit
  node-src/index.ts
  node-src/tasks/gitInfo.ts
Labels: release, minor

#1133 Bail on preview file changes
  node-src/lib/getDependentStoryFiles.test.ts
  node-src/lib/getDependentStoryFiles.ts
Labels: release, minor

#1136 Add `outputDir` to GitHub Action options
  action-src/main.ts
Labels: release, patch

#1138 Add rsbuild v0.1.7 support
  node-src/lib/getDependentStoryFiles.test.ts
  node-src/lib/getDependentStoryFiles.ts
  node-src/lib/getStorybookMetadata.ts
Labels: release, patch

#1140 Skip lock file parsing if it's larger than 10MB
  node-src/lib/findChangedDependencies.test.ts
  node-src/lib/getDependencies.test.ts
  node-src/lib/getDependencies.ts
Labels: release, minor

#1141 Log Turbosnap metrics to New Relic
  node-src/lib/newRelic.ts
  node-src/tasks/upload.ts
Labels: release, minor

#1142 Remove Turbosnap metrics logs
  node-src/lib/newRelic.ts
  node-src/tasks/upload.ts
Labels: release, patch

#1145 Account for accessibility change counts in UI
  node-src/types.ts
  node-src/ui/messages/errors/buildHasChanges.stories.ts
  node-src/ui/messages/errors/buildHasChanges.ts
  node-src/ui/messages/info/buildPassed.stories.ts
  node-src/ui/messages/info/buildPassed.ts
Labels: patch, skip-release

#1147 Add additional rspack builder entrypoint
  node-src/lib/getDependentStoryFiles.test.ts
  node-src/lib/getDependentStoryFiles.ts
Labels: release, patch

#1148 Fix directory flags for trace command.
  bin-src/trace.ts
Labels: patch, skip-release
