Repository chromaui/chromatic-cli, pull requests merged in 2025-02, with the labels that each got.

#1151 Set Apollo GraphQL client identification headers
  node-src/index.ts
Labels: patch, skip-release

#1155 Add new Vite builder entry for future SB versions
  node-src/lib/getDependentStoryFiles.test.ts
  node-src/lib/getDependentStoryFiles.ts
Labels: patch, skip-release

#1158 Upgrade to latest version of `snyk-nodejs-lockfile-parser`
  package.json
  yarn.lock
Labels: release, minor

#1157 Fix moduleName resolution for Storybook files with import cycles.
  node-src/lib/getDependentStoryFiles.test.ts
  node-src/lib/getDependentStoryFiles.ts
  node-src/types.ts
Labels: release, patch
