Repository chromaui/chromatic-cli, pull requests merged in 2025-07, with the labels that each got.

#1194 Dynamically generate `CHROMATIC_NOTIFY_SERVICE_URL`
  node-src/lib/getEnvironment.test.ts
  node-src/lib/getEnvironment.ts
Labels: patch, skip-release

#1191 Get build progress updates through Chromatic notify service
  node-src/lib/getEnvironment.test.ts
  node-src/lib/getEnvironment.ts
  node-src/lib/waitForBuildToComplete.test.ts
  node-src/lib/waitForBuildToComplete.ts
  node-src/tasks/snapshot.test.ts
  node-src/tasks/snapshot.ts
  package.json
  yarn.lock
Labels: release, minor

#1196 Skip notify service if there are no tests
  node-src/tasks/snapshot.test.ts
  node-src/tasks/snapshot.ts
Labels: release, patch

#1195 Copy package files with absolute paths
  node-src/lib/turbosnap/findChangedDependencies.test.ts
  node-src/lib/turbosnap/findChangedDependencies.ts
Labels: release, patch

#1197 Replace ad hoc test loggers with `TestLogger`
  node-src/git/getCommitAndBranch.test.ts
  node-src/lib/getStorybookInfo.test.ts
  node-src/lib/testLogger.ts
  node-src/lib/turbosnap/getDependentStoryFiles.test.ts
  node-src/lib/turbosnap/index.test.ts
  node-src/tasks/build.test.ts
  node-src/tasks/gitInfo.test.ts
  node-src/tasks/initialize.test.ts
  node-src/tasks/prepare.test.ts
  node-src/tasks/prepareWorkspace.test.ts
  node-src/tasks/report.test.ts
  node-src/tasks/snapshot.test.ts
  node-src/tasks/upload.test.ts
  node-src/tasks/verify.test.ts
Labels: patch, skip-release
