Repository chromaui/chromatic-cli, pull requests merged in 2025-03, with the labels that each got.

#1160 Add PNPM Support for TurboSnap
  .github/workflows/chromatic-main-and-prs.yml
  .github/workflows/chromatic-prod.yml
  .github/workflows/lint-and-test.yml
  .github/workflows/package-size-main.yml
  .github/workflows/package-size.yml
  .github/workflows/smoke-test-action-next.yml
  .github/workflows/smoke-test-action.yml
  .github/workflows/smoke-test-npx.yml
  .github/workflows/smoke-test-windows.yml
  .github/workflows/smoke-test-yarn-berry.yml
  .github/workflows/smoke-test-yarn-canary.yml
  .github/workflows/smoke-test-yarn-classic.yml
  .github/workflows/smoke-test-yarn.yml
  node-src/__mocks__/dependencyChanges/berry-chalk/package.json
  node-src/__mocks__/dependencyChanges/berry-chalk/yarn.lock
  node-src/__mocks__/dependencyChanges/berry/package.json
  node-src/__mocks__/dependencyChanges/berry/yarn.lock
  node-src/__mocks__/dependencyChanges/plain/package.json
  node-src/__mocks__/dependencyChanges/plain/yarn.lock
  node-src/__mocks__/dependencyChanges/react-async-10/package.json
  node-src/__mocks__/dependencyChanges/react-async-10/yarn.lock
  node-src/__mocks__/dependencyChanges/react-async-9/package.json
  node-src/__mocks__/dependencyChanges/react-async-9/yarn.lock
  node-src/git/git.ts
  node-src/lib/compareBaseline.test.ts
  node-src/lib/compareBaseline.ts
  node-src/lib/findChangedDependencies.test.ts
  node-src/lib/findChangedDependencies.ts
  node-src/lib/getDependencies.test.ts
  node-src/lib/getDependencies.ts
  package.json
  yarn.lock
Labels: release, minor

#1161 Throw on multiple scanned projects from snyk
  node-src/lib/getDependencies.test.ts
  node-src/lib/getDependencies.ts
Labels: minor, skip-release

#1162 Move TurboSnap to a local lib
  bin-src/trace.ts
  node-src/lib/turbosnap/compareBaseline.test.ts
  node-src/lib/turbosnap/compareBaseline.ts
  node-src/lib/turbosnap/findChangedDependencies.test.ts
  node-src/lib/turbosnap/findChangedDependencies.ts
  node-src/lib/turbosnap/findChangedPackageFiles.test.ts
  node-src/lib/turbosnap/findChangedPackageFiles.ts
  node-src/lib/turbosnap/getDependencies.test.ts
  node-src/lib/turbosnap/getDependencies.ts
  node-src/lib/turbosnap/getDependentStoryFiles.test.ts
  node-src/lib/turbosnap/getDependentStoryFiles.ts
  node-src/lib/turbosnap/index.test.ts
  node-src/lib/turbosnap/index.ts
  node-src/tasks/upload.test.ts
  node-src/tasks/upload.ts
  package.json
  tsconfig.json
  vitest.config.mts
  yarn.lock
Labels: minor, skip-release

#1163 Improve TurboSnap tests
  node-src/__mocks__/dependencyParsing/package-lock.json
  node-src/__mocks__/dependencyParsing/package.json
  node-src/__mocks__/dependencyParsing/pnpm-lock.yaml
  node-src/__mocks__/dependencyParsing/yarn.lock
  node-src/lib/turbosnap/compareBaseline.test.ts
  node-src/lib/turbosnap/compareBaseline.ts
  node-src/lib/turbosnap/findChangedDependencies.test.ts
  node-src/lib/turbosnap/findChangedDependencies.ts
  node-src/lib/turbosnap/getDependencies.test.ts
Labels: patch, skip-release

#1164 Add `pnpm-lock.yaml` to list of lockfiles
  node-src/lib/turbosnap/getDependentStoryFiles.test.ts
  node-src/lib/turbosnap/getDependentStoryFiles.ts
Labels: minor, skip-release
