Repository chromaui/chromatic-cli, pull requests merged in 2025-04, with the labels that each got.

#1167 Remove unused `viewLayer` and `addons` from CLI metadata
  node-src/lib/getPrebuiltStorybookMetadata.test.ts
  node-src/lib/getPrebuiltStorybookMetadata.ts
  node-src/lib/getStorybookInfo.test.ts
  node-src/lib/getStorybookMetadata.ts
  node-src/lib/supportedAddons.ts
Labels: release, minor

#1169 :pencil2: Update help text to reflect actual state of exitOnceUploaded.
  node-src/ui/messages/info/speedUpCI.ts
Labels: tiny, patch, skip-release

#1174 Return additional build info on action rerun
  node-src/index.ts
  node-src/tasks/gitInfo.test.ts
  node-src/tasks/gitInfo.ts
  node-src/types.ts
Labels: bug, release, patch

#1175 Use pagination to get all tests in the build
  node-src/tasks/report.test.ts
  node-src/tasks/report.ts
Labels: release, patch
